Dodo: dodo::core::GLFWContext Class Reference
dodo::core::GLFWContext Class Reference
#include <GLFWContext.hpp>
Public Member Functions
~GLFWContext ()
GLFWContext (const GLFWContext &other)=delete
GLFWContext & operator= (const GLFWContext &other)=delete
GLFWContext (GLFWContext &&other) noexcept
GLFWContext & operator= (GLFWContext &&other) noexcept
Private Member Functions
GLFWContext ()=default
Static Private Member Functions
static auto createContext () -> std::expected< GLFWContext, std::string >
Private Attributes
bool _ownsContext = false
Static Private Attributes
static bool _initialized = false
Friends
class DodoContext
Constructor & Destructor Documentation
~GLFWContext()
dodo::core::GLFWContext::~GLFWContext ()
{
    if (_ownsContext) {
        glfwTerminate();
        _initialized = false;
    }
}
References _initialized, _ownsContext, and glfwTerminate().
GLFWContext() [1/3]
dodo::core::GLFWContext::GLFWContext (const GLFWContext & other) delete
GLFWContext() [2/3]
dodo::core::GLFWContext::GLFWContext (GLFWContext && other) noexcept
    : _ownsContext(std::exchange(other._ownsContext, false)) {}
GLFWContext() [3/3]
dodo::core::GLFWContext::GLFWContext () private default
Member Function Documentation
createContext()
auto dodo::core::GLFWContext::createContext () -> std::expected<GLFWContext, std::string> static private
{
    if (_initialized) return std::unexpected("GLFW is already initialized");
    if (const char* errorBuf; !glfwInit()) {
        glfwGetError(&errorBuf);
        return std::unexpected(errorBuf);
    }
    _initialized = true;
    return GLFWContext();
}
References glfwGetError(), and glfwInit().
Referenced by dodo::core::DodoContext::createDodoContext().
operator=() [1/2]
GLFWContext & dodo::core::GLFWContext::operator= (const GLFWContext & other) delete
operator=() [2/2]
GLFWContext & dodo::core::GLFWContext::operator= (GLFWContext && other) noexcept
{
    if (this != &other) _ownsContext = std::exchange(other._ownsContext, false);
    return *this;
}
Friends And Related Symbol Documentation
DodoContext
friend class DodoContext friend
Member Data Documentation
_initialized
bool dodo::core::GLFWContext::_initialized = false inline static private
Referenced by ~GLFWContext().
_ownsContext
bool dodo::core::GLFWContext::_ownsContext = false private
Referenced by ~GLFWContext().
The documentation for this class was generated from the following files:
/github/workspace/include/dodo/core/GLFWContext.hpp
/github/workspace/src/dodo/core/GLFWContext.cpp