Dodo: dodo::core::DodoContext Class Reference
dodo::core::DodoContext Class Reference
#include <DodoContext.hpp>
Public Member Functions
~DodoContext ()=default
DodoContext (const DodoContext &other)=delete
DodoContext & operator= (const DodoContext &other)=delete
DodoContext (DodoContext &&other) noexcept
DodoContext & operator= (DodoContext &&other) noexcept
Static Public Member Functions
template<typename... Features>
static auto createDodoContext (const VulkanContext::VulkanContextInfo< Features... > &ctxInfo) -> std::expected< DodoContext, std::string >
Private Member Functions
DodoContext ()=default
Private Attributes
GLFWContext _glfwContext
VulkanContext _vulkanContext
Constructor & Destructor Documentation
DodoContext() [1/3]
dodo::core::DodoContext::DodoContext () private default
~DodoContext()
dodo::core::DodoContext::~DodoContext () default
DodoContext() [2/3]
dodo::core::DodoContext::DodoContext (const DodoContext & other) delete
DodoContext() [3/3]
dodo::core::DodoContext::DodoContext (DodoContext && other) noexcept
                                                    :
_glfwContext(std::move(other._glfwContext)),
_vulkanContext(std::move(other._vulkanContext))
{
}
Member Function Documentation
createDodoContext()
template<typename... Features> auto dodo::core::DodoContext::createDodoContext (const VulkanContext::VulkanContextInfo< Features... > & ctxInfo) -> std::expected<DodoContext, std::string> static
{
    auto glfwContext = GLFWContext::createContext();
    if (!glfwContext)
        return std::unexpected("Failed to create GLFW context: " + glfwContext.error());
    auto vulkanContext = VulkanContext::createContext(ctxInfo);
    if (!vulkanContext)
        return std::unexpected("Failed to create Vulkan context: " + vulkanContext.error());
    DodoContext dodoContext;
    dodoContext._glfwContext = std::move(*glfwContext);
    dodoContext._vulkanContext = std::move(*vulkanContext);
    return dodoContext;
}
References _glfwContext, _vulkanContext, dodo::core::GLFWContext::createContext(), and dodo::core::VulkanContext::createContext().
Referenced by main().
operator=() [1/2]
DodoContext & dodo::core::DodoContext::operator= (const DodoContext & other) delete
operator=() [2/2]
DodoContext & dodo::core::DodoContext::operator= (DodoContext && other) noexcept
{
    if (this != &other) {
        _glfwContext = std::move(other._glfwContext);
        _vulkanContext = std::move(other._vulkanContext);
    }
    return *this;
}
Member Data Documentation
_glfwContext
GLFWContext dodo::core::DodoContext::_glfwContext private
Referenced by createDodoContext().
_vulkanContext
VulkanContext dodo::core::DodoContext::_vulkanContext private
Referenced by createDodoContext().
The documentation for this class was generated from the following files:
/github/workspace/include/dodo/core/DodoContext.hpp
/github/workspace/src/dodo/core/DodoContext.cpp