Dodo: dodo::core::App Class Reference
dodo::core::App Class Reference
#include <App.hpp>
Classes
struct AppInfo
Public Member Functions
~App ()
App (const App &other)=delete
App & operator= (const App &other)=delete
App (App &&other) noexcept
App & operator= (App &&other) noexcept
bool isRunning () const
void pollEvents () const
Static Public Member Functions
static auto createApp (const DodoContext &ctx, const AppInfo &appInfo) -> std::expected< App, std::string >
Private Member Functions
App ()=default
auto createGLFWWindow (const AppInfo &appInfo) -> std::expected< bool, std::string >
Private Attributes
GLFWwindow * _window = nullptr
Constructor & Destructor Documentation
~App()
dodo::core::App::~App ()
          {
    if (_window)
        glfwDestroyWindow(_window);
}
References _window, and glfwDestroyWindow().
App() [1/3]
dodo::core::App::App (const App & other) delete
App() [2/3]
dodo::core::App::App (App && other) noexcept
                            :
_window(std::exchange(other._window, nullptr))
{
}
App() [3/3]
dodo::core::App::App () private default
Member Function Documentation
createApp()
auto dodo::core::App::createApp (const DodoContext & ctx, const AppInfo & appInfo) -> std::expected<App, std::string> static
{
    App app;
    if (auto result = app.createGLFWWindow(appInfo); !result)
        return std::unexpected(result.error());
    return app;
}
References createGLFWWindow().
Referenced by main().
createGLFWWindow()
auto dodo::core::App::createGLFWWindow (const AppInfo & appInfo) -> std::expected<bool, std::string> private
{
    const char *errorBuf;
    glfwWindowHint(GLFW_CLIENT_API, GLFW_NO_API);
    _window = glfwCreateWindow(appInfo.width, appInfo.height, appInfo.title.c_str(), appInfo.monitor, nullptr);
    if (!_window) {
        glfwGetError(&errorBuf);
        return std::unexpected(std::format("Failed to create GLFW Window: {}", errorBuf));
    }
    return true;
}
References GLFW_CLIENT_API, GLFW_NO_API, glfwCreateWindow(), glfwGetError(), and glfwWindowHint().
Referenced by createApp().
isRunning()
bool dodo::core::App::isRunning () const inline
{ return !glfwWindowShouldClose(_window); };
References _window, and glfwWindowShouldClose().
operator=() [1/2]
App & dodo::core::App::operator= (App && other) noexcept
{
    _window = std::exchange(other._window, nullptr);
    return *this;
}
operator=() [2/2]
App & dodo::core::App::operator= (const App & other) delete
pollEvents()
void dodo::core::App::pollEvents () const inline
{ glfwPollEvents(); };
References glfwPollEvents().
Member Data Documentation
_window
GLFWwindow* dodo::core::App::_window = nullptr private
Referenced by isRunning(), and ~App().
The documentation for this class was generated from the following files:
/github/workspace/include/dodo/core/App.hpp
/github/workspace/src/dodo/core/App.cpp