Dodo: dodo::core::VulkanContext Class Reference
dodo::core::VulkanContext Class Reference
#include <VulkanContext.hpp>
Classes
struct VulkanContextInfo
struct VulkanDebug
Public Types
using DebugCallback = vk::PFN_DebugUtilsMessengerCallbackEXT
Public Member Functions
~VulkanContext ()=default
VulkanContext (const VulkanContext &other)=delete
VulkanContext & operator= (const VulkanContext &other)=delete
VulkanContext (VulkanContext &&other) noexcept
VulkanContext & operator= (VulkanContext &&other) noexcept
Static Public Member Functions
static VKAPI_ATTR vk::Bool32 VKAPI_CALL defaultDebugCallback (vk::DebugUtilsMessageSeverityFlagBitsEXT severity, vk::DebugUtilsMessageTypeFlagsEXT type, const vk::DebugUtilsMessengerCallbackDataEXT *pCallbackData, void *)
template<typename... Features>
static auto createContext (const VulkanContextInfo< Features... > &ctxInfo, const std::experimental::observer_ptr< GLFWwindow > &window) -> std::expected< VulkanContext, std::string >
Private Member Functions
VulkanContext ()=default
auto createInstance (const vk::ApplicationInfo &vkInfo, const VulkanDebug &debugInfo) -> std::expected< bool, std::string >
auto checkRequiredLayers (std::span< const char *const > validationLayers) const -> std::expected< bool, std::string >
auto checkRequiredExtensions (std::span< const char *const > glfwExtensions) const -> std::expected< bool, std::string >
void setupDebugMessenger (DebugCallback debugCallback)
auto pickPhysicalDevice (const std::vector< const char * > &deviceExtensions) -> std::expected< bool, std::string >
auto findGraphicQueueFamily (const vk::raii::PhysicalDevice &physicalDevice) const -> std::expected< uint32_t, std::string >
auto findPresentationQueueFamily (const vk::raii::PhysicalDevice &physicalDevice, uint32_t &graphicsIndex) const -> std::expected< uint32_t, std::string >
template<typename... Features>
auto createLogicalDevice (const VulkanContextInfo< Features ... > &ctxInfo) -> std::expected< bool, std::string >
auto createSurface (const std::experimental::observer_ptr< GLFWwindow > &window) -> std::expected< bool, std::string >
Static Private Member Functions
static bool isDeviceSuitable (const vk::raii::PhysicalDevice &physicalDevice)
template<typename FirstFeature , typename... OtherFeatures>
static FirstFeature & getFirstFeature (vk::StructureChain< FirstFeature, OtherFeatures... > featureChain)
Private Attributes
vk::raii::Context _context
vk::raii::Instance _instance = nullptr
vk::raii::PhysicalDevice _physicalDevice = nullptr
vk::raii::DebugUtilsMessengerEXT _debugMessenger = nullptr
vk::raii::Device _device = nullptr
vk::raii::Queue _graphicsQueue = nullptr
vk::raii::Queue _presentationQueue = nullptr
vk::raii::SurfaceKHR _surface = nullptr
Friends
class DodoContext
Member Typedef Documentation
DebugCallback
using dodo::core::VulkanContext::DebugCallback = vk::PFN_DebugUtilsMessengerCallbackEXT
Constructor & Destructor Documentation
~VulkanContext()
dodo::core::VulkanContext::~VulkanContext () default
VulkanContext() [1/3]
dodo::core::VulkanContext::VulkanContext (const VulkanContext & other) delete
VulkanContext() [2/3]
dodo::core::VulkanContext::VulkanContext (VulkanContext && other) noexcept
                                                          :
_context(std::exchange(other._context, vk::raii::Context())),
_instance(std::exchange(other._instance, nullptr)),
_physicalDevice(std::exchange(other._physicalDevice, nullptr)),
_debugMessenger(std::exchange(other._debugMessenger, nullptr)),
_device(std::exchange(other._device, nullptr)),
_graphicsQueue(std::exchange(other._graphicsQueue, nullptr)),
_presentationQueue(std::exchange(other._presentationQueue, nullptr)),
_surface(std::exchange(other._surface, nullptr))
{
}
VulkanContext() [3/3]
dodo::core::VulkanContext::VulkanContext () private default
Member Function Documentation
checkRequiredExtensions()
auto dodo::core::VulkanContext::checkRequiredExtensions (std::span< const char *const > glfwExtensions) const -> std::expected<bool, std::string> private
{
    auto extensionProperties = _context.enumerateInstanceExtensionProperties();
    std::cout << "available extensions:\n";
    for (const auto &[extensionName, specVersion] : extensionProperties) {
        std::cout << '\t' << extensionName << " " << specVersion << '\n';
    }
    for (auto glfwExtension : glfwExtensions) {
        if (std::ranges::none_of(extensionProperties,
                                 [glfwExtension](auto const& extensionProperty)
                                 { return strcmp(extensionProperty.extensionName, glfwExtension) == 0; })) {
            return std::unexpected("Required GLFW extension not supported: " + std::string(glfwExtension));
        }
    }
    return true;
}
checkRequiredLayers()
auto dodo::core::VulkanContext::checkRequiredLayers (std::span< const char *const > validationLayers) const -> std::expected<bool, std::string> private
{
    if (!validationLayers.empty()) {
        auto layerProperties = _context.enumerateInstanceLayerProperties();
        if (std::ranges::any_of(validationLayers, [&layerProperties](auto const &requiredLayer) {
            return std::ranges::none_of(layerProperties, [requiredLayer](auto const &layerProperty) {
                return strcmp(layerProperty.layerName, requiredLayer) == 0;
            });
        })) {
            return std::unexpected("One or more required layers are not supported!");
        }
    }
    return true;
}
References validationLayers.
createContext()
template<typename... Features> auto dodo::core::VulkanContext::createContext (const VulkanContextInfo< Features... > & ctxInfo, const std::experimental::observer_ptr< GLFWwindow > & window) -> std::expected<VulkanContext, std::string> static
{
    VulkanContext vulkanContext;
    if (auto result = vulkanContext.createInstance(ctxInfo.vkInfo, ctxInfo.debugInfo); !result)
        return std::unexpected(result.error());
    if (auto result = vulkanContext.createSurface(window); !result)
        return std::unexpected(result.error());
    if (auto result = vulkanContext.pickPhysicalDevice(ctxInfo.deviceExtensions); !result)
        return std::unexpected(result.error());
    if (auto result = vulkanContext.createLogicalDevice(ctxInfo); !result)
        return std::unexpected(result.error());
    return vulkanContext;
}
References createInstance(), createLogicalDevice(), createSurface(), and pickPhysicalDevice().
Referenced by dodo::core::DodoContext::createDodoContext(), and main().
createInstance()
auto dodo::core::VulkanContext::createInstance (const vk::ApplicationInfo & vkInfo, const VulkanDebug & debugInfo) -> std::expected<bool, std::string> private
{
    uint32_t glfwExtensionCount = 0;
    const auto glfwExtensions = glfwGetRequiredInstanceExtensions(&glfwExtensionCount);
    std::vector extensions(glfwExtensions, glfwExtensions + glfwExtensionCount);
    if (debugInfo.debugEnabled) {
        if (auto result = checkRequiredLayers(debugInfo.validationLayers); !result)
            return std::unexpected(result.error());
        extensions.push_back(vk::EXTDebugUtilsExtensionName);
    }
    if (auto result = checkRequiredExtensions(std::span(extensions)); !result)
        return std::unexpected(result.error());
    const vk::InstanceCreateInfo createInfo{
        .pApplicationInfo = &vkInfo,
        .enabledLayerCount = static_cast<uint32_t>(debugInfo.validationLayers.size()),
        .ppEnabledLayerNames = debugInfo.validationLayers.data(),
        .enabledExtensionCount = static_cast<uint32_t>(extensions.size()),
        .ppEnabledExtensionNames = extensions.data(),
    };
    _instance = vk::raii::Instance(_context, createInfo);
    if (debugInfo.debugEnabled)
        setupDebugMessenger(debugInfo.debugCallback);
    return true;
}
References glfwGetRequiredInstanceExtensions().
Referenced by createContext().
createLogicalDevice()
template<typename... Features> auto dodo::core::VulkanContext::createLogicalDevice (const VulkanContextInfo< Features ... > & ctxInfo) -> std::expected<bool, std::string> private
{
    auto graphicsIndex = findGraphicQueueFamily(_physicalDevice);
    if (!graphicsIndex.has_value())
        return std::unexpected(graphicsIndex.error());
    auto presentationIndex = findPresentationQueueFamily(_physicalDevice, *graphicsIndex);
    if (!presentationIndex.has_value())
        return std::unexpected(presentationIndex.error());
    constexpr float queuePriority = 1.0F;
    vk::DeviceQueueCreateInfo deviceQueueCreateInfo { .queueFamilyIndex = *graphicsIndex, .queueCount = 1, .pQueuePriorities = &queuePriority };
    const vk::DeviceCreateInfo deviceCreateInfo{
        .pNext = &getFirstFeature(ctxInfo.featureChain),
        .queueCreateInfoCount = 1,
        .pQueueCreateInfos = &deviceQueueCreateInfo,
        .enabledExtensionCount = static_cast<uint32_t>(ctxInfo.deviceExtensions.size()),
        .ppEnabledExtensionNames = ctxInfo.deviceExtensions.data()
    };
    _device = vk::raii::Device(_physicalDevice, deviceCreateInfo);
    _graphicsQueue = vk::raii::Queue(_device, *graphicsIndex, 0);
    _presentationQueue = vk::raii::Queue(_device, *presentationIndex, 0);
    return true;
}
Referenced by createContext().
createSurface()
auto dodo::core::VulkanContext::createSurface (const std::experimental::observer_ptr< GLFWwindow > & window) -> std::expected<bool, std::string> private
{
    VkSurfaceKHR surface;
    if (glfwCreateWindowSurface(*_instance, window.get(), nullptr, &surface) != 0)
        return std::unexpected("failed to create window surface!");
    _surface = vk::raii::SurfaceKHR(_instance, surface);
    return true;
}
Referenced by createContext().
defaultDebugCallback()
VKAPI_ATTR vk::Bool32 VKAPI_CALL dodo::core::VulkanContext::defaultDebugCallback (vk::DebugUtilsMessageSeverityFlagBitsEXT severity, vk::DebugUtilsMessageTypeFlagsEXT type, const vk::DebugUtilsMessengerCallbackDataEXT * pCallbackData, void *) static
{
    if (severity >= vk::DebugUtilsMessageSeverityFlagBitsEXT::eWarning)
        std::cerr << "validation layer: type " << to_string(type) << " msg: " << pCallbackData->pMessage << std::endl;
    return vk::False;
}
findGraphicQueueFamily()
auto dodo::core::VulkanContext::findGraphicQueueFamily (const vk::raii::PhysicalDevice & physicalDevice) const -> std::expected<uint32_t, std::string> private
{
   const std::vector<vk::QueueFamilyProperties> queueFamilyProperties = physicalDevice.getQueueFamilyProperties();
    auto graphicsQueueFamilyProperty =
      std::find_if( queueFamilyProperties.begin(),
                    queueFamilyProperties.end(),
                    []( vk::QueueFamilyProperties const & qfp ) { return qfp.queueFlags & vk::QueueFlagBits::eGraphics; } );
    if (graphicsQueueFamilyProperty == queueFamilyProperties.end())
        return std::unexpected("No graphics queue family found");
    return static_cast<uint32_t>(std::distance(queueFamilyProperties.begin(), graphicsQueueFamilyProperty));
}
findPresentationQueueFamily()
auto dodo::core::VulkanContext::findPresentationQueueFamily (const vk::raii::PhysicalDevice & physicalDevice, uint32_t & graphicsIndex) const -> std::expected<uint32_t, std::string> private
{
    const std::vector<vk::QueueFamilyProperties> queueFamilyProperties = physicalDevice.getQueueFamilyProperties();
    const size_t queueFamilyPropertiesCount = queueFamilyProperties.size();
    auto presentationIndex = physicalDevice.getSurfaceSupportKHR(graphicsIndex, *_surface)
    ? graphicsIndex : static_cast<uint32_t>(queueFamilyProperties.size());
    if (presentationIndex == queueFamilyPropertiesCount) {
        for (size_t i = 0; i < queueFamilyPropertiesCount; i++) {
            if((queueFamilyProperties[i].queueFlags & vk::QueueFlagBits::eGraphics) &&
                physicalDevice.getSurfaceSupportKHR(static_cast<uint32_t>(i), *_surface)) {
                graphicsIndex = static_cast<uint32_t>(i);
                presentationIndex = graphicsIndex;
                break;
            }
        }
        if (presentationIndex == queueFamilyPropertiesCount) {
            for (size_t i = 0; i < queueFamilyPropertiesCount; i++) {
                if (physicalDevice.getSurfaceSupportKHR( static_cast<uint32_t>( i ), *_surface)) {
                    presentationIndex = static_cast<uint32_t>( i );
                    break;
                }
            }
        }
    }
    if (graphicsIndex == queueFamilyPropertiesCount)
        return std::unexpected("Could not find a queue family for graphics");
    if (presentationIndex == queueFamilyPropertiesCount)
        return std::unexpected("Could not find a queue family for presentation");
    return  presentationIndex;
}
getFirstFeature()
template<typename FirstFeature , typename... OtherFeatures> FirstFeature & dodo::core::VulkanContext::getFirstFeature (vk::StructureChain< FirstFeature, OtherFeatures... > featureChain) static private
{
    return featureChain.template get<FirstFeature>();
}
isDeviceSuitable()
bool dodo::core::VulkanContext::isDeviceSuitable (const vk::raii::PhysicalDevice & physicalDevice) static private
{
    const auto deviceProperties = physicalDevice.getProperties();
    const auto deviceFeatures = physicalDevice.getFeatures();
    return deviceProperties.deviceType == vk::PhysicalDeviceType::eDiscreteGpu && deviceFeatures.geometryShader;
}
operator=() [1/2]
VulkanContext & dodo::core::VulkanContext::operator= (const VulkanContext & other) delete
operator=() [2/2]
VulkanContext & dodo::core::VulkanContext::operator= (VulkanContext && other) noexcept
{
    if (this != &other) {
        _context = std::exchange(other._context, vk::raii::Context());
        _instance = std::exchange(other._instance, nullptr);
        _physicalDevice = std::exchange(other._physicalDevice, nullptr);
        _debugMessenger = std::exchange(other._debugMessenger, nullptr);
        _device = std::exchange(other._device, nullptr);
        _graphicsQueue = std::exchange(other._graphicsQueue, nullptr);
        _presentationQueue = std::exchange(other._presentationQueue, nullptr);
        _surface = std::exchange(other._surface, nullptr);
    }
    return *this;
}
pickPhysicalDevice()
auto dodo::core::VulkanContext::pickPhysicalDevice (const std::vector< const char * > & deviceExtensions) -> std::expected<bool, std::string> private
{
    auto devices = _instance.enumeratePhysicalDevices();
    const auto devIter = std::ranges::find_if(devices,
    [&](auto const & device) {
            auto queueFamilies = device.getQueueFamilyProperties();
            bool isSuitable = device.getProperties().apiVersion >= VK_API_VERSION_1_3;
            const auto qfpIter = std::ranges::find_if(queueFamilies,
            []( vk::QueueFamilyProperties const &qfp){
                return (qfp.queueFlags & vk::QueueFlagBits::eGraphics) != static_cast<vk::QueueFlags>(0);
            });
            isSuitable = isSuitable && (qfpIter != queueFamilies.end());
            auto extensions = device.enumerateDeviceExtensionProperties();
            bool found = true;
            for (auto const &extension : deviceExtensions) {
                auto extensionIter = std::ranges::find_if(extensions, [extension](auto const & ext) {return strcmp(ext.extensionName, extension) == 0;});
                found = found && extensionIter != extensions.end();
            }
            isSuitable = isSuitable && found;
            if (isSuitable)
                _physicalDevice = device;
            return isSuitable;
    });
    if (devIter == devices.end())
        return std::unexpected("Failed to find a suitable GPU");
    return true;
}
Referenced by createContext().
setupDebugMessenger()
void dodo::core::VulkanContext::setupDebugMessenger (DebugCallback debugCallback) private
{
    // TODO: Move this out of function
    constexpr vk::DebugUtilsMessageSeverityFlagsEXT SEVERITY_FLAGS(
        vk::DebugUtilsMessageSeverityFlagBitsEXT::eVerbose |
        vk::DebugUtilsMessageSeverityFlagBitsEXT::eWarning |
        vk::DebugUtilsMessageSeverityFlagBitsEXT::eError
    );
    constexpr vk::DebugUtilsMessageTypeFlagsEXT MESSAGE_TYPE_FLAGS(
            vk::DebugUtilsMessageTypeFlagBitsEXT::eGeneral |
            vk::DebugUtilsMessageTypeFlagBitsEXT::ePerformance |
            vk::DebugUtilsMessageTypeFlagBitsEXT::eValidation
    );
    const vk::DebugUtilsMessengerCreateInfoEXT debugUtilsMessengerCreateInfoEXT{
        .messageSeverity = SEVERITY_FLAGS,
        .messageType = MESSAGE_TYPE_FLAGS,
        .pfnUserCallback = debugCallback
    };
    _debugMessenger = _instance.createDebugUtilsMessengerEXT(debugUtilsMessengerCreateInfoEXT);
}
References _debugMessenger, and _instance.
Friends And Related Symbol Documentation
DodoContext
friend class DodoContext friend
Member Data Documentation
_context
vk::raii::Context dodo::core::VulkanContext::_context private
_debugMessenger
vk::raii::DebugUtilsMessengerEXT dodo::core::VulkanContext::_debugMessenger = nullptr private
Referenced by setupDebugMessenger().
_device
vk::raii::Device dodo::core::VulkanContext::_device = nullptr private
_graphicsQueue
vk::raii::Queue dodo::core::VulkanContext::_graphicsQueue = nullptr private
_instance
vk::raii::Instance dodo::core::VulkanContext::_instance = nullptr private
Referenced by setupDebugMessenger().
_physicalDevice
vk::raii::PhysicalDevice dodo::core::VulkanContext::_physicalDevice = nullptr private
_presentationQueue
vk::raii::Queue dodo::core::VulkanContext::_presentationQueue = nullptr private
_surface
vk::raii::SurfaceKHR dodo::core::VulkanContext::_surface = nullptr private
The documentation for this class was generated from the following files:
/github/workspace/include/dodo/core/VulkanContext.hpp
/github/workspace/src/dodo/core/VulkanContext.cpp